import NavBar from '@/components/NavBar'
import './globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="bg-slate-800 flex min-h-screen flex-col items-center p-24 text-white">
          {children}
        </main>
      </body>
    </html>
  )
}
