import './globals.css'
import Link from "next/link"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <nav>
          <ul className="flex flex-col space-y-4 bg-slate-900 text-white">
            <li>
              <Link className={"p-2"} href="/characters">List Characters</Link>
            </li>
          </ul>
        </nav>

        <main className="bg-slate-600 flex min-h-screen flex-col items-center p-24 text-white">
          {children}
        </main>
      </body>
    </html>
  )
}
